version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"


phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y maven
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - export M2=brew --prefix maven/libexec/bin
      - export M2_HOME=brew --prefix maven/libexec
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - sample.war
  discard-paths: yes
